[workspace]
authors = ["kaspermunch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge", "bioconda", "gwforg", "munch-group", "genomedk"]
name = "hic-xy-sperm"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
gwf = "*"
ipython = "*"
jupyterlab = "*"
pytables = "*"
scipy = "*"
seaborn = "*"
statsmodels = "*"
hicexplorer = "*"
bwa = "*"
cooler = "*"
samtools = "*"
jupyter = "*"
bowtie2 = "*"
natsort = "*"
pybigwig = "*"
pairtools = ">=1.1.3,<2"
multiqc = "*"
pprintpp = "*"
cooltools = "*"
genome-intervals = ">=0.1.7,<0.2"
geneinfo = ">=5.6.5,<6"
tabulate = "*"
pybbi = "*"
tinytex = "*"
genomepy = ">=0.16.3,<0.17"
git = "*"
gh = "*"
pip = "*"
git-lfs = "*"
cryptography = "*"
nodejs = "*"
ipykernel = "*"
nbconvert = "*"
vscodenb = ">=0.1.26,<0.2"
r-rsvg = "*"
pyranges = ">=0.1.4,<0.2"


[tasks.init]
cmd = "python ./scripts/rename.py && gh repo set-default \"https://github.com/munch-group/$(basename `git rev-parse --show-toplevel`)\""

[tasks.docs]
cmd = "./scripts/docs-run-notebooks.sh && git add -u notebooks"
description = "Run documentation notebooks"

[tasks.clean]
cmd = "git clean -id"
description = "Removes untracked files and directories but respects your .gitignores"

[tasks.commit]
depends-on = ["docs"]
cmd = "./scripts/git-commit.sh"
description = "Commits with message made by Claude"
